### ISSUE TITLE
프로젝트 기획서 최신화 요청

### ISSUE THREAD

**Issue by dMario24** [pladata-encore/DE32_LAST_DANCE#10]
@각팀 형상관리자(AA) 
- #8 에 따라 모든 팀원의 표시이름 변경 부탁드립니다.

- https://github.com/pladata-encore/DE32_LAST_DANCE/issues/7 에 따른 
- 공유 문서함에 문서가 등록되지 않거나 최신화 되지 않은 팀의 최신화 요청

## 확인대상
- [x] t1
- [x] t2
- [x] t3
- [x] t5

**Comment by j25ng** [comment]
3팀 프로젝트 기획서 업로드했습니다.

**Comment by WhiteCapella** [comment]
5팀 업로드 완료했습니다.

**Comment by oddsummer56** [comment]
1팀 업로드 완료했습니다.

**Comment by EstherCho-7** [comment]
2팀 업로드 완료했습니다.

**Comment by dMario24** [comment]
![LGTM](https://i.lgtm.fun/2urc.png)

네 감사합니다. 팀번호 스타일이 들쭉 날쭉 하지만 ^^ 넘어가요 ~
![image](https://github.com/user-attachments/assets/dd556921-aa4f-4585-af50-bd7133f76902)

**Comment by DONGUK777** [comment]
2조 업로드 완료했습니다
