### ISSUE TITLE
요구사항 정의서 및 WBS

### ISSUE THREAD

**Issue by dMario24** [pladata-encore/DE32_LAST_DANCE#11]
@all 

- 공유문서함 요구사항정의서 및 WBS 샘플을 참조하여
- 공유달력의 일정과 같이 제출 부탁드립니다.
- 제출 방법은 공유문서함 업로드 & 아래 체크박스 확인

# 요구사항정의서 제출 확인
- [x] T1
- [x] T2
- [x] T3
- [x] T4
- [x] T5

# WBS 제출 확인
- [x] T1
- [x] T2
- [x] T3
- [x] T4
- [x] T5

**Comment by dMario24** [comment]
# 의견
- [ ] 변경사항 추적을 위해 각 문서에 아래와 같은 내용 추가 필요
- [ ] 프로젝트 진행 과정에서 요구사항에 없거나 다른 개발이 진행 되지 않도록 관리 필요

![image](https://github.com/user-attachments/assets/97bd9313-d5b0-4180-8a27-0badacd04f93)

**Comment by dMario24** [comment]
# 1, 4 팀 WBS 올려주세요
- 별도 관리 하는 경우 빈문서를 만들어 링크를 기입하여 주세요.
![image](https://github.com/user-attachments/assets/d7df93a2-338b-45b9-9a2f-4835b3bdaa99)

# 1팀 요구사항정의 역시 업데이트 부탁드립니다.

@Jeonghoon2 @Mingk42

**Comment by oddsummer56** [comment]
업데이트 완료했습니다!

**Comment by dMario24** [comment]
4조 WBS 별도 관리에 대한 DM 보냄

**Comment by dMario24** [comment]
# 검토의견
- [ ] 기획서, 요구사항 및 WBS 의 변경사항 추가 필요
