### ISSUE TITLE
AC 회의 1차 - 안건 공유(집중 근무시간 정하기외)

### ISSUE THREAD

**Issue by dMario24** [pladata-encore/DE32_LAST_DANCE#13]
### 집중근무시간
- AC [미팅](https://calendar.google.com/calendar/u/0/r/eventedit/MW40aTc0NDZudXN2Z3JkazI5NzVpOHZwZm5fMjAyNDExMThUMDEwMDAwWiA4M2Y2NzBiZGM2ZTJmOWI3MjQ2NjFmNzVmYmMyNGZjNjY3YzRkZWU4OWRkOWEwM2U2ZmIzYjY5ZDAzZDIzYjQyQGc?cid=ODNmNjcwYmRjNmUyZjliNzI0NjYxZjc1ZmJjMjRmYzY2N2M0ZGVlODlkZDlhMDNlNmZiM2I2OWQwM2QyM2I0MkBncm91cC5jYWxlbmRhci5nb29nbGUuY29t) 통해 진행

### 엑션아이템
- 칸반보드 운영

**Comment by sooj1n** [comment]
# 집중 근무 시간
(오전) 10:00 ~ 12:50
(오후) 15:00~16:50

**Comment by dMario24** [comment]
#19 으로 이관하고 종료합니다.
- 빠르게 논의하고 결정해 주셔서 감사합니다. 😊
