### ISSUE TITLE
TL 회의 안건 공유 - 1차

### ISSUE THREAD

**Issue by dMario24** [pladata-encore/DE32_LAST_DANCE#18]
### 일시 및 장소
- 11/20 13:50~ 14:00 ( 매주 수요일 같은 시간 )
- 안내 데스크 옆 회의실

### 안건
- [ ] 사용 기술 스택 공유 회 ( 회의 전 댓글로 간략 요약을 올려 주시면 더 좋아요 )
- TL 비밀 미션 전달

### 엑션 아이템
- [ ] 다음번 회의 까지 본 별도 이슈 댓글로 아키텍처(안) 제출
- [ ] 별도 이슈는 @hamsunwoo 1조 TL 님이 생성(아래와 같은 제목) 부탁 드립니다 ( 돌아가면서 진행 예정 )
- [ ] TL 회의 안건 공유 - 2차 - 아키텍처 자랑 회
- [ ] 우리 아키텍처의 대안은? (TL 혼자 몰래 생각하고 바꾸진 않는다)

## 우리 아키텍처의 대안 - 시나리오
- 갑작 스럽게 데모가 대표님 요청으로 3일 후로 잡혔다. 일단 돌아가게 해야 한다. 이럴때 TL 이 이렇게 해보죠. 라고 대안을 마련한다
- 예상 보다 프로젝트 진도가 지지 부진하다.  출시일은 미룰 수 없다고 PM 이 그런다. 좀더 일정을 빠르게 진척 시길 방법이 있을까?

**Comment by j25ng** [comment]
### 3조 기술 스택
- FE : Flutter(Dart)
- BE : FastAPI, WebSocket

**Comment by GITSangWoo** [comment]
### 2조 기술 스택
- DE: Airflow,spark,teserect(OCR),ML(BERT)
- DA: Tableau(with trino),grafana
- BE :fastapi,Spring
- FE: HTML,CSS, JavaScript

**Comment by hamsunwoo** [comment]
## 1조 기술 스택 
- DE: Airflow,spark,kafka
- DA: Tableau(Database)
- BE :fastapi
- FE: HTML

**Comment by tbongkim03** [comment]
## 5조 기술 스택
- DE : Kafka, Airflow, Apache Spark 
- NLP : Python(konlpy), Speech to Text(KoSpeech or KT Speech Recognition API)
- BE : Fastapi
- FE : html, css, js (vue.js로 마이그레이션 할 예정), leaflet.js(지도)

**Comment by dMario24** [comment]
- https://github.com/pladata-encore/DE32_LAST_DANCE/issues/21 이후 회의 안건 상정으로 종료 합니다.

**Comment by lsiwh37249** [comment]
### 4조 기술 스택

DE : Kafka, Airflow, Apache Spark
NLP : Tensorflow
BE : Springboot, FastApi
FE : html, css, streamlit
