### ISSUE TITLE
AWS S3 사용 관련 질문드립니다.

### ISSUE THREAD

**Issue by Mingk42** [pladata-encore/DE32_LAST_DANCE#22]
AWS S3를 사용하려고 하는데 2가지 궁금증이 있습니다.

1. 해당 사용량도 조회해주실 수 있는지
2. S3의 경우 GB단위로 과금 + 각 호출 1000건 별로 과금인 것으로 파악했는데 예산 범위 내에서 사용가능할 지 궁금합니다.
> 대략적으로 봤을 때 예산 범위 내에서 사용 가능한 것으로 보이긴 하는데 정확하게 파악하는 것이 좋을 것 같아서요

**Comment by Mingk42** [comment]
https://aws.amazon.com/ko/s3/pricing/?nc=sn&loc=4

**Comment by dMario24** [comment]
- 우선 S3 는 저렴하다. 라고 생각하고 사용하셔도 됩니다. 50TB 저장시 월간 1$ 미만 ...
- 다만 s3 의 데이터가 외부로 나가는 경우 - 로컬컴퓨터에서 읽거나 ... 하는 경우 과금이 발생하며, 아주 큰 데이터가 아닌경우는 신경쓸 정도의 비용은 발생하지 않아요. 다만 s3 접근을 위한 key 가 노출되어 외부에서 해당 데이터를 다양 엑세스 하는 경우는 조심하셔야 합니다.
- 해당 사용량도 조회가 가능합니다. 2 ~ 3 일 주기로 사용량 리포트를 이슈에 올려드리겠습니다.

**Comment by dMario24** [comment]
https://github.com/pladata-encore/DE32_LAST_DANCE/issues/29#issuecomment-2496450640

위 링크 s3 사용 비용 확인해 보면 감이 올겁니다.
