### ISSUE TITLE
에어플로우 컴포즈로 실행 시 브로커 연결 문제

### ISSUE THREAD

**Issue by hamsunwoo** [pladata-encore/DE32_LAST_DANCE#25]
에러메세지
```bash
Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
```

에어플로우 env 설정 
```bash
x-airflow-common-env: &airflow-common-env
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor
  AIRFLOW__CORE__FERNET_KEY: ''
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: 'postgresql+psycopg2://airflow:airflow@postgres/airflow'
  AIRFLOW__CELERY__BROKER_URL: 'redis://redis:6379/0'
  AIRFLOW__CELERY__RESULT_BACKEND: 'db+postgresql://airflow:airflow@postgres/airflow'
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
  AIRFLOW__WEBSERVER__DEFAULT_USER: "true"
```

에어플로우를 컴포즈로 실행하면 브로커 연결이 필요한데 브로커를 redis로 설정해두었는데 계속 RabbitMQ 브로커 연결이 실패하였다는 에러메세지를 받고있습니다.

**Comment by dMario24** [comment]
- 그래서 웹서버는 동작하나 워커가 task 를 다음 단계로 진행하지 못하는 문제가 있음

**Comment by dMario24** [comment]
# 해결
- 공식가이드의 yaml 의 worker 부분의 cmd 부분과 이를 위해 컨테이너 수행 권한을 root 로 변경하면서 발생한 문제입니다. 
- 항상 문제가 발생하면 문제와 에러로그를 참조하되 직전 변경사항이 무엇인지 확인이 필요합니다.
- 본 질문에도 문제를 야기한 변경사항에 대한 언급이나 설정 파일 없이 로그와 증상만 있는 부분은 차후 실무에도 적절한 전후 상황에 대한 기술이 필요한점 확인 부탁드립니다.

# 요약
- [ ] 증상만 보고 해결하기 어려움
- [ ] 실무에서도 증상 만으로 문의 하는 것은 좋지 않음

# 팁
- 실무 상황에서 사수에서 문의한 부분에 대해 차후 해결 되면 어떻게 해결 되었는지도 공유해야 상황이 종료되는 것임을 인지하면 좋겠음 ^^ 질문만 하고 결과를 회신 하지 않으면 차후 질문을 잘 받아 주지 않음 ...

**Comment by hamsunwoo** [comment]
## 결과 
worker 이미지를 Dockerfile 을 별도로 만들어 빌드
```bash
FROM apache/airflow:2.10.3

USER root
RUN apt update && apt install -y git

USER airflow
```
