### ISSUE TITLE
Day 1 프로젝트 기획서 및 킥오프

### ISSUE THREAD

**Issue by dMario24** [pladata-encore/DE32_LAST_DANCE#7]
![image](https://github.com/user-attachments/assets/27d5f15e-ae33-49fb-aa51-2c364b642da1)

- [프로젝트 공유일정](https://calendar.google.com/calendar/u/0?cid=ODNmNjcwYmRjNmUyZjliNzI0NjYxZjc1ZmJjMjRmYzY2N2M0ZGVlODlkZDlhMDNlNmZiM2I2OWQwM2QyM2I0MkBncm91cC5jYWxlbmRhci5nb29nbGUuY29t)

- [프로젝트 공유문서](https://drive.google.com/drive/folders/1GgGjHdtOV-75hA63sfjJdtQX49QpWD7v?usp=sharing)

# Day
- [ ] one-page 기획서 작성 - 위 공유 문서함 - 기획서_샘플 참고 1 page 로 작성
- [ ] 기획서 25 copy 출력 Hands on 배포 후 5시 부터 프로젝트 시작 발표 & semi final 프로젝트 공유 각 팀 7분
- [ ] 아래 comment 에 기획서 링크 제출
- [ ] PR close 되지 않은 부분도 확인

![image](https://github.com/user-attachments/assets/2ab1dc60-f4d8-4fd4-94aa-7276acc32d50)

**Comment by Mingk42** [comment]
[Team1_프로젝트 기획안](https://docs.google.com/document/d/1E7B2R3uNjATN77irU_t7qra51NG_Ijki/)

**Comment by j25ng** [comment]
- [Team3_프로젝트 기획안](https://docs.google.com/document/d/1hMJVtWqaUh22LkCb7y4-vxYI-9_9bjbb/edit#heading=h.f3v99qvfixgt)

**Comment by sooj1n** [comment]
- [Team5_프로젝트 기획안](https://docs.google.com/document/d/14YM0q4AyrZy9V0gsETgnM2M9eSFAnqLC59CWNGX6CEc/edit?usp=drive_link)

**Comment by DONGUK777** [comment]
- [Team2_프로젝트 기획안](https://github.com/DE32FinalTeam2/FinalRepo/blob/dev/md/md_file/1_%EA%B8%B0%ED%9A%8D%EC%84%9C.md)

**Comment by dMario24** [comment]
발표 및 공유 완료
